plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.112'
}

group = 'com.braedon'
version = project.mod_version

base {
    archivesName = 'vm-betternether-rubyfire-compat'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neoforge_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
